/* V9.10 — MULTI-DEVICE DATA FOUNDATION — client foundation only; no cloud sync yet. */
(function(){
'use strict';
if(window.__v910MultiDeviceFoundation)return;
const DB_KEY='fnb_manager_v1',META_KEY='fnb_v910_meta',QUEUE_KEY='fnb_v910_queue',CONFLICT_KEY='fnb_v910_conflicts';
const COLLECTIONS=['ingredients','recipes','products','plans','sales','cash','batches'];
function read(k,f){try{const v=JSON.parse(localStorage.getItem(k));return v==null?f:v}catch(e){return f}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function makeId(p){return p+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8)}
function hash(v){const s=JSON.stringify(v);let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return ('00000000'+(h>>>0).toString(16)).slice(-8)}
let meta=read(META_KEY,{});if(!meta.deviceId)meta.deviceId=makeId('device');if(!meta.createdAt)meta.createdAt=new Date().toISOString();if(!meta.serverVersion)meta.serverVersion=null;write(META_KEY,meta);
function queue(){return read(QUEUE_KEY,[])} function conflicts(){return read(CONFLICT_KEY,[])}
function currentUser(){try{return window.v9state?.()?.user?.username||'local-user'}catch(e){return'local-user'}}
function branchId(){try{return window.v9state?.()?.branchId||'MAIN'}catch(e){return'MAIN'}}
function snapshot(){try{return JSON.parse(localStorage.getItem(DB_KEY)||'{}')}catch(e){return{}}}
function byId(a){const m={};(Array.isArray(a)?a:[]).forEach(x=>{if(x&&x.id!=null)m[String(x.id)]=x});return m}
function addQueue(op){const q=queue();q.push(op);write(QUEUE_KEY,q);meta.lastJournalAt=op.at;write(META_KEY,meta);renderStatus()}
function journalDiff(before,after){const at=new Date().toISOString();COLLECTIONS.forEach(c=>{const a=byId(before[c]),b=byId(after[c]);const ids=new Set([...Object.keys(a),...Object.keys(b)]);ids.forEach(id=>{const oldVal=a[id],newVal=b[id];if(!oldVal&&newVal)addQueue({opId:makeId('op'),type:'create',entity:c,entityId:id,after:newVal,beforeHash:null,deviceId:meta.deviceId,username:currentUser(),branchId:branchId(),at});else if(oldVal&&!newVal)addQueue({opId:makeId('op'),type:'delete',entity:c,entityId:id,after:null,beforeHash:hash(oldVal),deviceId:meta.deviceId,username:currentUser(),branchId:branchId(),at});else if(oldVal&&newVal&&hash(oldVal)!==hash(newVal))addQueue({opId:makeId('op'),type:'update',entity:c,entityId:id,after:newVal,beforeHash:hash(oldVal),deviceId:meta.deviceId,username:currentUser(),branchId:branchId(),at})})});if(hash(before.settings||{})!==hash(after.settings||{}))addQueue({opId:makeId('op'),type:'update',entity:'settings',entityId:'app',after:after.settings||{},beforeHash:hash(before.settings||{}),deviceId:meta.deviceId,username:currentUser(),branchId:branchId(),at})}
const originalSave=window.save;if(typeof originalSave==='function'){window.save=function(){const before=snapshot();const result=originalSave.apply(this,arguments);const after=snapshot();try{journalDiff(before,after)}catch(e){console.warn('V9.10 journal',e)}return result}}
function setNetworkBadge(){let b=document.getElementById('v910NetworkBadge');if(!b){b=document.createElement('div');b.id='v910NetworkBadge';b.style.cssText='position:fixed;right:18px;bottom:18px;z-index:190;background:#fff;border:1px solid var(--line,#e4e9e6);border-radius:999px;padding:7px 11px;font-size:12px;font-weight:800;box-shadow:0 6px 18px rgba(0,0,0,.08)';document.body.appendChild(b)}const online=navigator.onLine!==false,p=queue().length,c=conflicts().length;b.textContent=c?'🔴 Xung đột '+c:online?(p?'🔵 Online · chờ '+p:'🟢 Online'):'🟠 Offline'+(p?' · chờ '+p:'');b.title=online?'Có kết nối mạng':'Đang dùng dữ liệu trên thiết bị'}
function renderStatus(){setNetworkBadge();const e=document.getElementById('v910SyncStatus');if(e){const q=queue().length,c=conflicts().length;e.innerHTML=(navigator.onLine!==false?'🟢 Online':'🟠 Offline')+' · '+q+' thay đổi đang chờ · '+c+' xung đột'}}
function settingsCard(){if(document.getElementById('v910DataCard'))return;const view=document.getElementById('view');if(!view)return;const title=(document.getElementById('topTitle')||{}).textContent||'';if(title.trim()!=='Cài đặt')return;const card=document.createElement('div');card.className='card';card.id='v910DataCard';card.style.marginTop='16px';card.innerHTML='<div class="section-title">🔄 Dữ liệu & đồng bộ</div><div id="v910SyncStatus" style="font-size:13px;margin:8px 0">Đang kiểm tra...</div><div style="font-size:12px;color:var(--muted);line-height:1.55">Thiết bị: <b>'+meta.deviceId+'</b><br>Chế độ hiện tại: <b>Tự động</b> — khi offline app dùng dữ liệu trên thiết bị.<br>Các thay đổi được ghi vào hàng đợi để xử lý khi cơ chế đồng bộ máy chủ được bật.</div><div class="toolbar" style="margin-top:12px"><button class="btn" id="v910ClearBtn">🧹 Xóa hàng đợi</button></div>';view.appendChild(card);document.getElementById('v910ClearBtn').onclick=window.v910ClearLocalQueue;renderStatus()}
window.v910GetState=function(){return{deviceId:meta.deviceId,online:navigator.onLine!==false,pending:queue(),conflicts:conflicts(),serverVersion:meta.serverVersion}}
window.v910ClearLocalQueue=function(){if(!confirm('Xóa hàng đợi thay đổi cục bộ? Chỉ làm việc này khi bạn chắc chắn các thay đổi đã được xử lý.'))return;write(QUEUE_KEY,[]);renderStatus();toast('Đã xóa hàng đợi cục bộ')}
window.addEventListener('online',()=>{setNetworkBadge();settingsCard()});window.addEventListener('offline',()=>{setNetworkBadge();settingsCard()});
const observer=new MutationObserver(()=>{settingsCard();renderStatus()});observer.observe(document.body,{childList:true,subtree:true});
window.__v910MultiDeviceFoundation=true;setTimeout(()=>{settingsCard();renderStatus()},100);setTimeout(()=>{settingsCard();renderStatus()},700);
})();
