/* F&B Manager V10 — staged delete/UX compatibility layer */
(function(){
  'use strict';
  const idFrom=(row,rx)=>{for(const b of row.querySelectorAll('button[onclick]')){const m=(b.getAttribute('onclick')||'').match(rx);if(m)return m[1]}return ''};
  const rerender=p=>{save();render(p)};
  function ingredient(id){const x=db.ingredients.find(i=>i.id===id);if(!x)return;if(db.recipes.some(r=>(r.lines||[]).some(l=>l.kind!=='recipe'&&l.ingredientId===id))){toast('Không thể xóa: nguyên liệu đang được dùng trong công thức.');return}if(!confirm(`Xóa nguyên liệu “${x.name}”?\nCác lô của nguyên liệu này cũng sẽ bị xóa.`))return;db.ingredients=db.ingredients.filter(i=>i.id!==id);db.batches=db.batches.filter(b=>b.ingredientId!==id);rerender('ingredients');toast('Đã xóa nguyên liệu')}
  function recipe(id){const x=db.recipes.find(r=>r.id===id);if(!x)return;if(db.products.some(p=>(p.components||[]).some(c=>c.recipeId===id))||db.recipes.some(r=>r.id!==id&&(r.lines||[]).some(l=>l.kind==='recipe'&&l.recipeId===id))){toast('Không thể xóa: công thức đang được sử dụng.');return}if(!confirm(`Xóa công thức “${x.name}”?`))return;db.recipes=db.recipes.filter(r=>r.id!==id);rerender('recipes');toast('Đã xóa công thức')}
  function product(id){const x=db.products.find(p=>p.id===id);if(!x)return;if(db.sales.some(o=>(o.items||[]).some(i=>i.pid===id))||db.plans.some(p=>(p.items||[]).some(i=>i.productId===id)||p.productId===id)){toast('Không thể xóa: sản phẩm đã có trong đơn hàng hoặc kế hoạch.');return}if(!confirm(`Xóa sản phẩm “${x.name}”?`))return;db.products=db.products.filter(p=>p.id!==id);rerender('products');toast('Đã xóa sản phẩm')}
  function customer(id){const x=db.customers.find(c=>c.id===id);if(!x)return;if(db.sales.some(o=>o.customerId===id)||db.debts.some(d=>d.customerId===id)){toast('Không thể xóa: khách hàng còn lịch sử mua hàng hoặc công nợ.');return}if(!confirm(`Xóa khách hàng “${x.name}”?`))return;db.customers=db.customers.filter(c=>c.id!==id);rerender('customers');toast('Đã xóa khách hàng')}
  function plan(id){const x=db.plans.find(p=>p.id===id);if(!x)return;if(['producing','completed'].includes(x.status)){toast('Không thể xóa kế hoạch đã bắt đầu hoặc hoàn thành.');return}if(!confirm(`Xóa kế hoạch “${x.name}”?`))return;db.plans=db.plans.filter(p=>p.id!==id);rerender('production');toast('Đã xóa kế hoạch')}
  function sale(id){const x=db.sales.find(o=>o.id===id);if(!x)return;if(!confirm(`Xóa hóa đơn #${String(id).slice(-6).toUpperCase()}?\nTồn kho sản phẩm sẽ được hoàn lại.`))return;(x.items||[]).forEach(i=>{const p=db.products.find(p=>p.id===i.pid);if(p)p.stock=(Number(p.stock)||0)+(Number(i.qty)||0)});db.sales=db.sales.filter(o=>o.id!==id);rerender('pos');toast('Đã xóa hóa đơn và hoàn tồn sản phẩm')}
  function batch(id){const x=db.batches.find(b=>b.id===id);if(!x)return;if(!confirm(`Xóa lô “${x.lot||id}”?`))return;db.batches=db.batches.filter(b=>b.id!==id);rerender('inventory');toast('Đã xóa lô nguyên liệu')}
  function employee(id){const x=db.employees.find(e=>e.id===id);if(!x)return;if(x.id===db.sessionEmployeeId){toast('Không thể xóa tài khoản nhân viên đang đăng nhập.');return}if(!confirm(`Xóa nhân viên “${x.name||x.username||id}”?`))return;db.employees=db.employees.filter(e=>e.id!==id);rerender('employees');toast('Đã xóa nhân viên')}
  window.FNB_DELETE={ingredient,recipe,product,customer,plan,sale,batch,employee};
  function inject(){
    const view=document.getElementById('view');if(!view)return;const page=document.querySelector('.nav button.active')?.dataset.page||'';
    const cfg={ingredients:[/ingredientModal\(['"]([^'"]+)/,'ingredient'],recipes:[/recipeDetailModal\(['"]([^'"]+)/,'recipe'],products:[/productModalV5\(['"]([^'"]+)/,'product'],customers:[/v8CustomerDetail\(['"]([^'"]+)/,'customer'],production:[/r4PlanDetail\(['"]([^'"]+)/,'plan'],pos:[/orderDetailModal\(['"]([^'"]+)/,'sale'],employees:[/v8EmployeeDetail\(['"]([^'"]+)/,'employee']}[page];
    if(cfg)view.querySelectorAll('.table tbody tr').forEach(row=>{if(row.dataset.fnbDelete)return;const action=row.lastElementChild;if(!action)return;const rid=idFrom(row,cfg[0]);if(!rid)return;const b=document.createElement('button');b.type='button';b.className='btn small danger';b.textContent='Xóa';b.onclick=e=>{e.preventDefault();e.stopPropagation();FNB_DELETE[cfg[1]](rid)};action.append(' ',b);row.dataset.fnbDelete='1'});
    if(page==='inventory')view.querySelectorAll('.table tbody tr').forEach(row=>{if(row.dataset.fnbDelete)return;const texts=[...row.cells].map(c=>c.innerText.trim());const x=db.batches.find(b=>b.lot&&texts.includes(String(b.lot).trim()));const a=row.lastElementChild;if(!x||!a)return;const b=document.createElement('button');b.type='button';b.className='btn small danger';b.textContent='Xóa';b.onclick=e=>{e.preventDefault();e.stopPropagation();FNB_DELETE.batch(x.id)};a.append(' ',b);row.dataset.fnbDelete='1'});
  }
  const mb=document.getElementById('modalBack');if(mb)mb.addEventListener('click',e=>{if(e.target===mb){e.preventDefault();e.stopImmediatePropagation()}},true);
  const obs=new MutationObserver(()=>requestAnimationFrame(inject));obs.observe(document.getElementById('view')||document.body,{childList:true,subtree:true});setTimeout(inject,0);
})();